In [17]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [4]:
c = pd.read_csv("complete.csv")
c = c.reset_index(drop = True)

In [ ]:
#c = c.drop(['Unnamed: 0'], axis = 1)
#c['is_target']=c['is_target'].fillna('repetition')
c

#train and test split:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

,file_id,Fp1,Fpz,Fp2,F7,F3,Fz,F4,F8,FC5,...,P8,POz,O1,Oz,O2,sub_num,word,prime,target,is_target
0,book_english-english_translation_1,0.105563,-10.123230,-13.193379,6.893438,-7.629562,28.292086,2.719152,-2.486754,-6.934687,...,2.177121,-12.258789,5.257230,0.080961,-1.445801,1,book,english,english,translation
1,book_english-english_translation_1,-3.794437,-9.431230,-12.219379,1.226438,-13.299563,13.985086,-1.569848,-7.682754,-4.498687,...,4.545121,-12.626789,4.125230,-0.084039,0.799199,1,book,english,english,translation
2,book_english-english_translation_1,-7.023438,-9.685230,-12.414379,-2.416562,-17.288563,6.112086,-3.922848,-10.316754,-3.801687,...,5.249121,-13.392789,2.746230,-0.500039,2.292199,1,book,english,english,translation
3,book_english-english_translation_1,-9.825437,-11.147230,-13.928379,-4.398562,-20.232563,3.905086,-4.680848,-10.806754,-4.979687,...,4.145121,-14.575789,1.150230,-1.167039,3.052199,1,book,english,english,translation
4,book_english-english_translation_1,-12.493438,-13.672230,-16.416379,-5.623563,-23.102563,4.827086,-4.590848,-10.200754,-7.615687,...,1.752121,-15.943789,-0.458770,-1.918039,3.352199,1,book,english,english,translation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5287675,lawyer_spanish-english_translation_14,-3.516820,-1.697895,-2.728246,-10.633723,-8.578855,-8.568699,-5.287813,-3.886641,-9.075684,...,5.424855,-1.044684,1.141414,-1.449102,1.209855,14,lawyer,spanish,english,translation
5287676,lawyer_spanish-english_translation_14,-0.936820,-0.116895,-3.095246,-7.548723,-7.357855,-7.782699,-3.605812,-2.518641,-6.969684,...,6.165855,-0.334684,2.041414,-0.141102,2.526855,14,lawyer,spanish,english,translation
5287677,lawyer_spanish-english_translation_14,3.418180,2.774105,-3.127246,-1.822723,-4.885855,-5.685699,-0.092812,-1.016641,-3.140684,...,7.705855,1.114316,3.840414,2.031898,4.475855,14,lawyer,spanish,english,translation
5287678,lawyer_spanish-english_translation_14,8.765180,6.430105,-2.895246,5.480277,-1.677855,-2.810699,4.534187,0.466359,1.778316,...,9.785855,3.016316,6.200414,4.731898,6.817855,14,lawyer,spanish,english,translation
5287679,lawyer_spanish-english_translation_14,8.765180,6.430105,-2.895246,5.480277,-1.677855,-2.810699,4.534187,0.466359,1.778316,...,9.785855,3.016316,6.200414,4.731898,6.817855,14,lawyer,spanish,english,translation

In [ ]:
meta = pd.read_csv("metadata.csv")

    participant  spanish  french  german  other
0             1        0       0       0      0
1             2        0       0       0      1
2             3        0       0       0      0
3             4        0       1       0      1
4             5        0       0       0      0
5             6        0       0       0      0
6             7        0       0       0      0
7             8        0       0       0      0
8             9        0       0       0      0
9            10        1       0       0      1
10           11        0       0       0      0
11           12        0       1       0      0
12           13        1       0       0      1
13           14        1       0       0      0
14           15        1       0       0      1
15           16        1       0       0      0
16           17        1       0       0      0
17           18        0       0       1      0
18           19        1       0       0      0
19           20        0       0       0      0
20           21        0       0       1      0
21           22        0       0       1      0
22           23        0       1       0      1
23           24        0       0       0      0
24           25        0       0       0      0
25           26        0       1       0      0
26           27        0       0       0      0
27           28        0       0       1      0
28           29        0       0       0      0
29           30        0       0       0      0
30           31        1       0       0      0
31           32        0       0       0      0
32           33        0       1       0      1
33           34        0       0       0      0
34           35        1       0       0      0
35           36        0       0       0      0
36           37        0       0       0      0
37           38        0       0       0      0
38           39        1       0       0      0
39           40        0       0       0      0

In [19]:
c.rename(columns={'sub_num': 'participant'}, inplace=True)

In [ ]:
c=c.merge(meta, on='participant', how='inner')

,file_id,Fp1,Fpz,Fp2,F7,F3,Fz,F4,F8,FC5,...,O2,participant,word,prime,target,is_target,spanish,french,german,other
0,book_english-english_translation_1,0.105563,-10.123230,-13.193379,6.893438,-7.629562,28.292086,2.719152,-2.486754,-6.934687,...,-1.445801,1,book,english,english,translation,0,0,0,0
1,book_english-english_translation_1,-3.794437,-9.431230,-12.219379,1.226438,-13.299563,13.985086,-1.569848,-7.682754,-4.498687,...,0.799199,1,book,english,english,translation,0,0,0,0
2,book_english-english_translation_1,-7.023438,-9.685230,-12.414379,-2.416562,-17.288563,6.112086,-3.922848,-10.316754,-3.801687,...,2.292199,1,book,english,english,translation,0,0,0,0
3,book_english-english_translation_1,-9.825437,-11.147230,-13.928379,-4.398562,-20.232563,3.905086,-4.680848,-10.806754,-4.979687,...,3.052199,1,book,english,english,translation,0,0,0,0
4,book_english-english_translation_1,-12.493438,-13.672230,-16.416379,-5.623563,-23.102563,4.827086,-4.590848,-10.200754,-7.615687,...,3.352199,1,book,english,english,translation,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5287675,yesterday_spanish-spanish_unrelated_24,-5.116543,-11.343855,-15.321680,-6.595898,-9.745852,-10.681402,-9.451781,-2.752324,-1.356699,...,-10.019977,24,yesterday,spanish,spanish,unrelated,0,0,0,0
5287676,yesterday_spanish-spanish_unrelated_24,-6.809543,-12.195855,-16.271680,-6.318898,-8.593852,-9.474402,-8.180781,-2.972324,-0.523699,...,-15.282977,24,yesterday,spanish,spanish,unrelated,0,0,0,0
5287677,yesterday_spanish-spanish_unrelated_24,-8.458543,-12.088855,-15.100680,-5.417898,-6.856852,-7.148402,-6.086781,-2.591324,0.534301,...,-20.131977,24,yesterday,spanish,spanish,unrelated,0,0,0,0
5287678,yesterday_spanish-spanish_unrelated_24,-10.121543,-11.435855,-12.655680,-4.065898,-4.749852,-4.186402,-3.580781,-1.880324,1.729301,...,-24.700977,24,yesterday,spanish,spanish,unrelated,0,0,0,0
5287679,yesterday_spanish-spanish_unrelated_24,-10.121543,-11.435855,-12.655680,-4.065898,-4.749852,-4.186402,-3.580781,-1.880324,1.729301,...,-24.700977,24,yesterday,spanish,spanish,unrelated,0,0,0,0

In [ ]:
c.to_csv('full.csv')