Data Cleaning and Imports

In [67]:
import pandas as pd
import re

In [38]:
df = pd.read_csv("combined_output.csv")

In [39]:
df

,Fp1,Fpz,Fp2,F7,F3,Fz,F4,F8,FC5,FC1,...,P7,P3,Pz,P4,P8,POz,O1,Oz,O2,file_id
0,0.105563,-10.123230,-13.193379,6.893438,-7.629562,28.292086,2.719152,-2.486754,-6.934687,-7.466992,...,-1.546625,-12.672410,-15.553527,-6.628602,2.177121,-12.258789,5.257230,0.080961,-1.445801,book_english-english_translation_1
1,-3.794437,-9.431230,-12.219379,1.226438,-13.299563,13.985086,-1.569848,-7.682754,-4.498687,-8.062992,...,-2.437625,-12.575410,-15.718527,-5.548602,4.545121,-12.626789,4.125230,-0.084039,0.799199,book_english-english_translation_1
2,-7.023438,-9.685230,-12.414379,-2.416562,-17.288563,6.112086,-3.922848,-10.316754,-3.801687,-8.833992,...,-4.136625,-13.252410,-16.214527,-5.214602,5.249121,-13.392789,2.746230,-0.500039,2.292199,book_english-english_translation_1
3,-9.825437,-11.147230,-13.928379,-4.398562,-20.232563,3.905086,-4.680848,-10.806754,-4.979687,-10.249992,...,-6.539625,-14.651410,-17.082527,-5.590602,4.145121,-14.575789,1.150230,-1.167039,3.052199,book_english-english_translation_1
4,-12.493438,-13.672230,-16.416379,-5.623563,-23.102563,4.827086,-4.590848,-10.200754,-7.615687,-12.606992,...,-9.277625,-16.380410,-18.129527,-6.305602,1.752121,-15.943789,-0.458770,-1.918039,3.352199,book_english-english_translation_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5287419,10.902852,10.721117,5.722645,10.143051,4.646547,4.687559,7.522605,4.315691,10.868324,9.599668,...,7.568828,9.960406,10.438281,6.176687,6.114793,10.411668,8.727711,5.741070,10.275480,yesterday_spanish-spanish_unrelated_8
5287420,11.663852,11.599117,6.500645,11.582051,5.349547,4.282559,6.428605,4.855691,13.146324,9.258668,...,8.800828,10.807406,11.632281,7.642688,6.446793,11.091668,10.018711,6.706070,10.610480,yesterday_spanish-spanish_unrelated_8
5287421,13.160852,13.258117,7.185645,13.325051,7.400547,4.465559,5.302605,4.940691,17.652324,9.840668,...,10.826828,12.537406,13.561281,10.380688,7.513793,12.651668,12.252711,8.591070,11.672480,yesterday_spanish-spanish_unrelated_8
5287422,15.170852,15.465117,7.863645,15.273051,10.337547,5.023559,4.181605,4.721691,23.653324,11.043668,...,13.386828,14.885406,15.977281,13.934688,9.075793,14.818668,15.111711,11.081070,13.241480,yesterday_spanish-spanish_unrelated_8
5287423,15.170852,15.465117,7.863645,15.273051,10.337547,5.023559,4.181605,4.721691,23.653324,11.043668,...,13.386828,14.885406,15.977281,13.934688,9.075793,14.818668,15.111711,11.081070,13.241480,yesterday_spanish-spanish_unrelated_8

In [68]:
def split_string_number(s):
    match = re.match(r'([^\d]+)(\d+)$', s)
    if match:
        return match.groups()
    else:
        return s, None

In [41]:
df[['strings', 'sub_num']] = df['file_id'].apply(split_string_number).apply(pd.Series)

In [42]:
df

,Fp1,Fpz,Fp2,F7,F3,Fz,F4,F8,FC5,FC1,...,Pz,P4,P8,POz,O1,Oz,O2,file_id,strings,sub_num
0,0.105563,-10.123230,-13.193379,6.893438,-7.629562,28.292086,2.719152,-2.486754,-6.934687,-7.466992,...,-15.553527,-6.628602,2.177121,-12.258789,5.257230,0.080961,-1.445801,book_english-english_translation_1,book_english-english_translation_,1
1,-3.794437,-9.431230,-12.219379,1.226438,-13.299563,13.985086,-1.569848,-7.682754,-4.498687,-8.062992,...,-15.718527,-5.548602,4.545121,-12.626789,4.125230,-0.084039,0.799199,book_english-english_translation_1,book_english-english_translation_,1
2,-7.023438,-9.685230,-12.414379,-2.416562,-17.288563,6.112086,-3.922848,-10.316754,-3.801687,-8.833992,...,-16.214527,-5.214602,5.249121,-13.392789,2.746230,-0.500039,2.292199,book_english-english_translation_1,book_english-english_translation_,1
3,-9.825437,-11.147230,-13.928379,-4.398562,-20.232563,3.905086,-4.680848,-10.806754,-4.979687,-10.249992,...,-17.082527,-5.590602,4.145121,-14.575789,1.150230,-1.167039,3.052199,book_english-english_translation_1,book_english-english_translation_,1
4,-12.493438,-13.672230,-16.416379,-5.623563,-23.102563,4.827086,-4.590848,-10.200754,-7.615687,-12.606992,...,-18.129527,-6.305602,1.752121,-15.943789,-0.458770,-1.918039,3.352199,book_english-english_translation_1,book_english-english_translation_,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5287419,10.902852,10.721117,5.722645,10.143051,4.646547,4.687559,7.522605,4.315691,10.868324,9.599668,...,10.438281,6.176687,6.114793,10.411668,8.727711,5.741070,10.275480,yesterday_spanish-spanish_unrelated_8,yesterday_spanish-spanish_unrelated_,8
5287420,11.663852,11.599117,6.500645,11.582051,5.349547,4.282559,6.428605,4.855691,13.146324,9.258668,...,11.632281,7.642688,6.446793,11.091668,10.018711,6.706070,10.610480,yesterday_spanish-spanish_unrelated_8,yesterday_spanish-spanish_unrelated_,8
5287421,13.160852,13.258117,7.185645,13.325051,7.400547,4.465559,5.302605,4.940691,17.652324,9.840668,...,13.561281,10.380688,7.513793,12.651668,12.252711,8.591070,11.672480,yesterday_spanish-spanish_unrelated_8,yesterday_spanish-spanish_unrelated_,8
5287422,15.170852,15.465117,7.863645,15.273051,10.337547,5.023559,4.181605,4.721691,23.653324,11.043668,...,15.977281,13.934688,9.075793,14.818668,15.111711,11.081070,13.241480,yesterday_spanish-spanish_unrelated_8,yesterday_spanish-spanish_unrelated_,8
5287423,15.170852,15.465117,7.863645,15.273051,10.337547,5.023559,4.181605,4.721691,23.653324,11.043668,...,15.977281,13.934688,9.075793,14.818668,15.111711,11.081070,13.241480,yesterday_spanish-spanish_unrelated_8,yesterday_spanish-spanish_unrelated_,8

In [43]:
split_cols = df['strings'].str.split(r'[_-]', expand=True)

In [44]:
split_cols

                 0        1        2            3 4
0             book  english  english  translation
1             book  english  english  translation
2             book  english  english  translation
3             book  english  english  translation
4             book  english  english  translation
...            ...      ...      ...          ... ..
5287419  yesterday  spanish  spanish    unrelated
5287420  yesterday  spanish  spanish    unrelated
5287421  yesterday  spanish  spanish    unrelated
5287422  yesterday  spanish  spanish    unrelated
5287423  yesterday  spanish  spanish    unrelated

[5287424 rows x 5 columns]

In [45]:
split_cols = split_cols.rename(columns = {0:'word', 1:'prime', 2:'target', 3:'is_target', 4:'idx'})

In [46]:
split_cols

              word    prime   target    is_target idx
0             book  english  english  translation
1             book  english  english  translation
2             book  english  english  translation
3             book  english  english  translation
4             book  english  english  translation
...            ...      ...      ...          ...  ..
5287419  yesterday  spanish  spanish    unrelated
5287420  yesterday  spanish  spanish    unrelated
5287421  yesterday  spanish  spanish    unrelated
5287422  yesterday  spanish  spanish    unrelated
5287423  yesterday  spanish  spanish    unrelated

[5287424 rows x 5 columns]

In [47]:
split_cols = split_cols[['word', 'prime', 'target', 'is_target']]

In [48]:
df = pd.concat([df, split_cols], axis=1)

In [49]:
df

,Fp1,Fpz,Fp2,F7,F3,Fz,F4,F8,FC5,FC1,...,O1,Oz,O2,file_id,strings,sub_num,word,prime,target,is_target
0,0.105563,-10.123230,-13.193379,6.893438,-7.629562,28.292086,2.719152,-2.486754,-6.934687,-7.466992,...,5.257230,0.080961,-1.445801,book_english-english_translation_1,book_english-english_translation_,1,book,english,english,translation
1,-3.794437,-9.431230,-12.219379,1.226438,-13.299563,13.985086,-1.569848,-7.682754,-4.498687,-8.062992,...,4.125230,-0.084039,0.799199,book_english-english_translation_1,book_english-english_translation_,1,book,english,english,translation
2,-7.023438,-9.685230,-12.414379,-2.416562,-17.288563,6.112086,-3.922848,-10.316754,-3.801687,-8.833992,...,2.746230,-0.500039,2.292199,book_english-english_translation_1,book_english-english_translation_,1,book,english,english,translation
3,-9.825437,-11.147230,-13.928379,-4.398562,-20.232563,3.905086,-4.680848,-10.806754,-4.979687,-10.249992,...,1.150230,-1.167039,3.052199,book_english-english_translation_1,book_english-english_translation_,1,book,english,english,translation
4,-12.493438,-13.672230,-16.416379,-5.623563,-23.102563,4.827086,-4.590848,-10.200754,-7.615687,-12.606992,...,-0.458770,-1.918039,3.352199,book_english-english_translation_1,book_english-english_translation_,1,book,english,english,translation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5287419,10.902852,10.721117,5.722645,10.143051,4.646547,4.687559,7.522605,4.315691,10.868324,9.599668,...,8.727711,5.741070,10.275480,yesterday_spanish-spanish_unrelated_8,yesterday_spanish-spanish_unrelated_,8,yesterday,spanish,spanish,unrelated
5287420,11.663852,11.599117,6.500645,11.582051,5.349547,4.282559,6.428605,4.855691,13.146324,9.258668,...,10.018711,6.706070,10.610480,yesterday_spanish-spanish_unrelated_8,yesterday_spanish-spanish_unrelated_,8,yesterday,spanish,spanish,unrelated
5287421,13.160852,13.258117,7.185645,13.325051,7.400547,4.465559,5.302605,4.940691,17.652324,9.840668,...,12.252711,8.591070,11.672480,yesterday_spanish-spanish_unrelated_8,yesterday_spanish-spanish_unrelated_,8,yesterday,spanish,spanish,unrelated
5287422,15.170852,15.465117,7.863645,15.273051,10.337547,5.023559,4.181605,4.721691,23.653324,11.043668,...,15.111711,11.081070,13.241480,yesterday_spanish-spanish_unrelated_8,yesterday_spanish-spanish_unrelated_,8,yesterday,spanish,spanish,unrelated
5287423,15.170852,15.465117,7.863645,15.273051,10.337547,5.023559,4.181605,4.721691,23.653324,11.043668,...,15.111711,11.081070,13.241480,yesterday_spanish-spanish_unrelated_8,yesterday_spanish-spanish_unrelated_,8,yesterday,spanish,spanish,unrelated

In [50]:
df.set_index('file_id', inplace = True)

In [51]:
print(df)

                                             Fp1        Fpz        Fp2  \
file_id
book_english-english_translation_1      0.105563 -10.123230 -13.193379
book_english-english_translation_1     -3.794437  -9.431230 -12.219379
book_english-english_translation_1     -7.023438  -9.685230 -12.414379
book_english-english_translation_1     -9.825437 -11.147230 -13.928379
book_english-english_translation_1    -12.493438 -13.672230 -16.416379
...                                          ...        ...        ...
yesterday_spanish-spanish_unrelated_8  10.902852  10.721117   5.722645
yesterday_spanish-spanish_unrelated_8  11.663852  11.599117   6.500645
yesterday_spanish-spanish_unrelated_8  13.160852  13.258117   7.185645
yesterday_spanish-spanish_unrelated_8  15.170852  15.465117   7.863645
yesterday_spanish-spanish_unrelated_8  15.170852  15.465117   7.863645

                                              F7         F3         Fz  \
file_id
book_english-english_translation_1      6.893438  -7.629562  28.292086
book_english-english_translation_1      1.226438 -13.299563  13.985086
book_english-english_translation_1     -2.416562 -17.288563   6.112086
book_english-english_translation_1     -4.398562 -20.232563   3.905086
book_english-english_translation_1     -5.623563 -23.102563   4.827086
...                                          ...        ...        ...
yesterday_spanish-spanish_unrelated_8  10.143051   4.646547   4.687559
yesterday_spanish-spanish_unrelated_8  11.582051   5.349547   4.282559
yesterday_spanish-spanish_unrelated_8  13.325051   7.400547   4.465559
yesterday_spanish-spanish_unrelated_8  15.273051  10.337547   5.023559
yesterday_spanish-spanish_unrelated_8  15.273051  10.337547   5.023559

                                             F4         F8        FC5  \
file_id
book_english-english_translation_1     2.719152  -2.486754  -6.934687
book_english-english_translation_1    -1.569848  -7.682754  -4.498687
book_english-english_translation_1    -3.922848 -10.316754  -3.801687
book_english-english_translation_1    -4.680848 -10.806754  -4.979687
book_english-english_translation_1    -4.590848 -10.200754  -7.615687
...                                         ...        ...        ...
yesterday_spanish-spanish_unrelated_8  7.522605   4.315691  10.868324
yesterday_spanish-spanish_unrelated_8  6.428605   4.855691  13.146324
yesterday_spanish-spanish_unrelated_8  5.302605   4.940691  17.652324
yesterday_spanish-spanish_unrelated_8  4.181605   4.721691  23.653324
yesterday_spanish-spanish_unrelated_8  4.181605   4.721691  23.653324

                                             FC1  ...        POz         O1  \
file_id                                           ...
book_english-english_translation_1     -7.466992  ... -12.258789   5.257230
book_english-english_translation_1     -8.062992  ... -12.626789   4.125230
book_english-english_translation_1     -8.833992  ... -13.392789   2.746230
book_english-english_translation_1    -10.249992  ... -14.575789   1.150230
book_english-english_translation_1    -12.606992  ... -15.943789  -0.458770
...                                          ...  ...        ...        ...
yesterday_spanish-spanish_unrelated_8   9.599668  ...  10.411668   8.727711
yesterday_spanish-spanish_unrelated_8   9.258668  ...  11.091668  10.018711
yesterday_spanish-spanish_unrelated_8   9.840668  ...  12.651668  12.252711
yesterday_spanish-spanish_unrelated_8  11.043668  ...  14.818668  15.111711
yesterday_spanish-spanish_unrelated_8  11.043668  ...  14.818668  15.111711

                                              Oz         O2  \
file_id
book_english-english_translation_1      0.080961  -1.445801
book_english-english_translation_1     -0.084039   0.799199
book_english-english_translation_1     -0.500039   2.292199
book_english-english_translation_1     -1.167039   3.052199
book_english-english_translation_1     -1.918039   3.352199
...                                          ...        ...
yesterday_spanish-spanish_unrelated_8   5.741070  10.275480
yesterday_spanish-spanish_unrelated_8   6.706070  10.610480
yesterday_spanish-spanish_unrelated_8   8.591070  11.672480
yesterday_spanish-spanish_unrelated_8  11.081070  13.241480
yesterday_spanish-spanish_unrelated_8  11.081070  13.241480

                                                                    strings  \
file_id
book_english-english_translation_1        book_english-english_translation_
book_english-english_translation_1        book_english-english_translation_
book_english-english_translation_1        book_english-english_translation_
book_english-english_translation_1        book_english-english_translation_
book_english-english_translation_1        book_english-english_translation_
...                                                                     ...
yesterday_spanish-spanish_unrelated_8  yesterday_spanish-spanish_unrelated_
yesterday_spanish-spanish_unrelated_8  yesterday_spanish-spanish_unrelated_
yesterday_spanish-spanish_unrelated_8  yesterday_spanish-spanish_unrelated_
yesterday_spanish-spanish_unrelated_8  yesterday_spanish-spanish_unrelated_
yesterday_spanish-spanish_unrelated_8  yesterday_spanish-spanish_unrelated_

                                       sub_num       word    prime   target  \
file_id
book_english-english_translation_1           1       book  english  english
book_english-english_translation_1           1       book  english  english
book_english-english_translation_1           1       book  english  english
book_english-english_translation_1           1       book  english  english
book_english-english_translation_1           1       book  english  english
...                                        ...        ...      ...      ...
yesterday_spanish-spanish_unrelated_8        8  yesterday  spanish  spanish
yesterday_spanish-spanish_unrelated_8        8  yesterday  spanish  spanish
yesterday_spanish-spanish_unrelated_8        8  yesterday  spanish  spanish
yesterday_spanish-spanish_unrelated_8        8  yesterday  spanish  spanish
yesterday_spanish-spanish_unrelated_8        8  yesterday  spanish  spanish

                                         is_target
file_id
book_english-english_translation_1     translation
book_english-english_translation_1     translation
book_english-english_translation_1     translation
book_english-english_translation_1     translation
book_english-english_translation_1     translation
...                                            ...
yesterday_spanish-spanish_unrelated_8    unrelated
yesterday_spanish-spanish_unrelated_8    unrelated
yesterday_spanish-spanish_unrelated_8    unrelated
yesterday_spanish-spanish_unrelated_8    unrelated
yesterday_spanish-spanish_unrelated_8    unrelated

[5287424 rows x 36 columns]

In [52]:
df

,Fp1,Fpz,Fp2,F7,F3,Fz,F4,F8,FC5,FC1,...,POz,O1,Oz,O2,strings,sub_num,word,prime,target,is_target
file_id,,,,,,,,,,,,,,,,,,,,,
book_english-english_translation_1,0.105563,-10.123230,-13.193379,6.893438,-7.629562,28.292086,2.719152,-2.486754,-6.934687,-7.466992,...,-12.258789,5.257230,0.080961,-1.445801,book_english-english_translation_,1,book,english,english,translation
book_english-english_translation_1,-3.794437,-9.431230,-12.219379,1.226438,-13.299563,13.985086,-1.569848,-7.682754,-4.498687,-8.062992,...,-12.626789,4.125230,-0.084039,0.799199,book_english-english_translation_,1,book,english,english,translation
book_english-english_translation_1,-7.023438,-9.685230,-12.414379,-2.416562,-17.288563,6.112086,-3.922848,-10.316754,-3.801687,-8.833992,...,-13.392789,2.746230,-0.500039,2.292199,book_english-english_translation_,1,book,english,english,translation
book_english-english_translation_1,-9.825437,-11.147230,-13.928379,-4.398562,-20.232563,3.905086,-4.680848,-10.806754,-4.979687,-10.249992,...,-14.575789,1.150230,-1.167039,3.052199,book_english-english_translation_,1,book,english,english,translation
book_english-english_translation_1,-12.493438,-13.672230,-16.416379,-5.623563,-23.102563,4.827086,-4.590848,-10.200754,-7.615687,-12.606992,...,-15.943789,-0.458770,-1.918039,3.352199,book_english-english_translation_,1,book,english,english,translation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
yesterday_spanish-spanish_unrelated_8,10.902852,10.721117,5.722645,10.143051,4.646547,4.687559,7.522605,4.315691,10.868324,9.599668,...,10.411668,8.727711,5.741070,10.275480,yesterday_spanish-spanish_unrelated_,8,yesterday,spanish,spanish,unrelated
yesterday_spanish-spanish_unrelated_8,11.663852,11.599117,6.500645,11.582051,5.349547,4.282559,6.428605,4.855691,13.146324,9.258668,...,11.091668,10.018711,6.706070,10.610480,yesterday_spanish-spanish_unrelated_,8,yesterday,spanish,spanish,unrelated
yesterday_spanish-spanish_unrelated_8,13.160852,13.258117,7.185645,13.325051,7.400547,4.465559,5.302605,4.940691,17.652324,9.840668,...,12.651668,12.252711,8.591070,11.672480,yesterday_spanish-spanish_unrelated_,8,yesterday,spanish,spanish,unrelated
yesterday_spanish-spanish_unrelated_8,15.170852,15.465117,7.863645,15.273051,10.337547,5.023559,4.181605,4.721691,23.653324,11.043668,...,14.818668,15.111711,11.081070,13.241480,yesterday_spanish-spanish_unrelated_,8,yesterday,spanish,spanish,unrelated
yesterday_spanish-spanish_unrelated_8,15.170852,15.465117,7.863645,15.273051,10.337547,5.023559,4.181605,4.721691,23.653324,11.043668,...,14.818668,15.111711,11.081070,13.241480,yesterday_spanish-spanish_unrelated_,8,yesterday,spanish,spanish,unrelated

In [53]:
df.drop(columns=['strings'])

,Fp1,Fpz,Fp2,F7,F3,Fz,F4,F8,FC5,FC1,...,P8,POz,O1,Oz,O2,sub_num,word,prime,target,is_target
file_id,,,,,,,,,,,,,,,,,,,,,
book_english-english_translation_1,0.105563,-10.123230,-13.193379,6.893438,-7.629562,28.292086,2.719152,-2.486754,-6.934687,-7.466992,...,2.177121,-12.258789,5.257230,0.080961,-1.445801,1,book,english,english,translation
book_english-english_translation_1,-3.794437,-9.431230,-12.219379,1.226438,-13.299563,13.985086,-1.569848,-7.682754,-4.498687,-8.062992,...,4.545121,-12.626789,4.125230,-0.084039,0.799199,1,book,english,english,translation
book_english-english_translation_1,-7.023438,-9.685230,-12.414379,-2.416562,-17.288563,6.112086,-3.922848,-10.316754,-3.801687,-8.833992,...,5.249121,-13.392789,2.746230,-0.500039,2.292199,1,book,english,english,translation
book_english-english_translation_1,-9.825437,-11.147230,-13.928379,-4.398562,-20.232563,3.905086,-4.680848,-10.806754,-4.979687,-10.249992,...,4.145121,-14.575789,1.150230,-1.167039,3.052199,1,book,english,english,translation
book_english-english_translation_1,-12.493438,-13.672230,-16.416379,-5.623563,-23.102563,4.827086,-4.590848,-10.200754,-7.615687,-12.606992,...,1.752121,-15.943789,-0.458770,-1.918039,3.352199,1,book,english,english,translation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
yesterday_spanish-spanish_unrelated_8,10.902852,10.721117,5.722645,10.143051,4.646547,4.687559,7.522605,4.315691,10.868324,9.599668,...,6.114793,10.411668,8.727711,5.741070,10.275480,8,yesterday,spanish,spanish,unrelated
yesterday_spanish-spanish_unrelated_8,11.663852,11.599117,6.500645,11.582051,5.349547,4.282559,6.428605,4.855691,13.146324,9.258668,...,6.446793,11.091668,10.018711,6.706070,10.610480,8,yesterday,spanish,spanish,unrelated
yesterday_spanish-spanish_unrelated_8,13.160852,13.258117,7.185645,13.325051,7.400547,4.465559,5.302605,4.940691,17.652324,9.840668,...,7.513793,12.651668,12.252711,8.591070,11.672480,8,yesterday,spanish,spanish,unrelated
yesterday_spanish-spanish_unrelated_8,15.170852,15.465117,7.863645,15.273051,10.337547,5.023559,4.181605,4.721691,23.653324,11.043668,...,9.075793,14.818668,15.111711,11.081070,13.241480,8,yesterday,spanish,spanish,unrelated
yesterday_spanish-spanish_unrelated_8,15.170852,15.465117,7.863645,15.273051,10.337547,5.023559,4.181605,4.721691,23.653324,11.043668,...,9.075793,14.818668,15.111711,11.081070,13.241480,8,yesterday,spanish,spanish,unrelated

In [ ]:
df.to_csv('merged_final.csv', index = True)

In [72]:
m = pd.read_csv("merged_final.csv")
m

,file_id,Fp1,Fpz,Fp2,F7,F3,Fz,F4,F8,FC5,...,POz,O1,Oz,O2,strings,sub_num,word,prime,target,is_target
0,book_english-english_translation_1,0.105563,-10.123230,-13.193379,6.893438,-7.629562,28.292086,2.719152,-2.486754,-6.934687,...,-12.258789,5.257230,0.080961,-1.445801,book_english-english_translation_,1,book,english,english,translation
1,book_english-english_translation_1,-3.794437,-9.431230,-12.219379,1.226438,-13.299563,13.985086,-1.569848,-7.682754,-4.498687,...,-12.626789,4.125230,-0.084039,0.799199,book_english-english_translation_,1,book,english,english,translation
2,book_english-english_translation_1,-7.023438,-9.685230,-12.414379,-2.416562,-17.288563,6.112086,-3.922848,-10.316754,-3.801687,...,-13.392789,2.746230,-0.500039,2.292199,book_english-english_translation_,1,book,english,english,translation
3,book_english-english_translation_1,-9.825437,-11.147230,-13.928379,-4.398562,-20.232563,3.905086,-4.680848,-10.806754,-4.979687,...,-14.575789,1.150230,-1.167039,3.052199,book_english-english_translation_,1,book,english,english,translation
4,book_english-english_translation_1,-12.493438,-13.672230,-16.416379,-5.623563,-23.102563,4.827086,-4.590848,-10.200754,-7.615687,...,-15.943789,-0.458770,-1.918039,3.352199,book_english-english_translation_,1,book,english,english,translation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5287419,yesterday_spanish-spanish_unrelated_8,10.902852,10.721117,5.722645,10.143051,4.646547,4.687559,7.522605,4.315691,10.868324,...,10.411668,8.727711,5.741070,10.275480,yesterday_spanish-spanish_unrelated_,8,yesterday,spanish,spanish,unrelated
5287420,yesterday_spanish-spanish_unrelated_8,11.663852,11.599117,6.500645,11.582051,5.349547,4.282559,6.428605,4.855691,13.146324,...,11.091668,10.018711,6.706070,10.610480,yesterday_spanish-spanish_unrelated_,8,yesterday,spanish,spanish,unrelated
5287421,yesterday_spanish-spanish_unrelated_8,13.160852,13.258117,7.185645,13.325051,7.400547,4.465559,5.302605,4.940691,17.652324,...,12.651668,12.252711,8.591070,11.672480,yesterday_spanish-spanish_unrelated_,8,yesterday,spanish,spanish,unrelated
5287422,yesterday_spanish-spanish_unrelated_8,15.170852,15.465117,7.863645,15.273051,10.337547,5.023559,4.181605,4.721691,23.653324,...,14.818668,15.111711,11.081070,13.241480,yesterday_spanish-spanish_unrelated_,8,yesterday,spanish,spanish,unrelated
5287423,yesterday_spanish-spanish_unrelated_8,15.170852,15.465117,7.863645,15.273051,10.337547,5.023559,4.181605,4.721691,23.653324,...,14.818668,15.111711,11.081070,13.241480,yesterday_spanish-spanish_unrelated_,8,yesterday,spanish,spanish,unrelated

In [59]:
m.isna().sum()

file_id          0
Fp1              0
Fpz              0
Fp2              0
F7               0
F3               0
Fz               0
F4               0
F8               0
FC5              0
FC1              0
FC2              0
FC6              0
T7               0
C3               0
Cz               0
C4               0
T8               0
CP5              0
CP1              0
CP2              0
CP6              0
P7               0
P3               0
Pz               0
P4               0
P8               0
POz              0
O1               0
Oz               0
O2               0
strings          0
sub_num          0
word             0
prime            0
target           0
is_target    10240
dtype: int64

In [60]:
m['is_target'].unique()

array(['translation', 'unrelated', nan], dtype=object)

In [65]:
na = m[(m['is_target'] != 'translation') & (m['is_target'] != 'unrelated')]
na

,file_id,Fp1,Fpz,Fp2,F7,F3,Fz,F4,F8,FC5,...,POz,O1,Oz,O2,strings,sub_num,word,prime,target,is_target
3346944,non-english_repetition_1,-2.639703,-1.170980,0.257297,-2.081984,-1.398953,-5.846332,-3.008926,-4.093785,-1.068121,...,-3.512441,-2.509590,-5.139301,-1.718523,non-english_repetition_,1,non,english,repetition,NaN
3346945,non-english_repetition_1,-0.790703,-0.248980,1.088297,-0.347984,1.047047,-1.317332,-0.997926,-2.196785,-0.347121,...,-2.931441,-1.810590,-4.548301,-0.992523,non-english_repetition_,1,non,english,repetition,NaN
3346946,non-english_repetition_1,0.549297,0.458020,1.724297,0.779016,2.647047,1.448668,0.388074,-0.938785,0.270879,...,-2.452441,-1.250590,-4.091301,-0.448523,non-english_repetition_,1,non,english,repetition,NaN
3346947,non-english_repetition_1,1.285297,0.856020,2.051297,1.224016,3.332047,2.453668,1.106074,-0.407785,0.657879,...,-2.122441,-0.875590,-3.808301,-0.139523,non-english_repetition_,1,non,english,repetition,NaN
3346948,non-english_repetition_1,1.442297,0.895020,1.980297,1.054016,3.249047,2.170668,1.260074,-0.557785,0.708879,...,-1.958441,-0.687590,-3.703301,-0.063523,non-english_repetition_,1,non,english,repetition,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3357179,non-english_repetition_9,-4.801746,-7.183227,-6.033105,-12.068125,-7.420758,0.745793,-3.528156,-2.965941,-1.992863,...,-2.619887,-0.520227,-4.264734,-8.216547,non-english_repetition_,9,non,english,repetition,NaN
3357180,non-english_repetition_9,-4.772746,-7.261227,-6.057105,-12.058125,-7.341758,0.823793,-3.392156,-2.875941,-1.866863,...,-2.610887,-0.439227,-4.314734,-8.271547,non-english_repetition_,9,non,english,repetition,NaN
3357181,non-english_repetition_9,-4.661746,-7.282227,-5.990105,-12.025125,-7.168758,0.954793,-3.083156,-2.679941,-1.731863,...,-2.639887,-0.437227,-4.438734,-8.356547,non-english_repetition_,9,non,english,repetition,NaN
3357182,non-english_repetition_9,-4.498746,-7.264227,-5.859105,-11.990125,-6.943758,1.109793,-2.667156,-2.415941,-1.606863,...,-2.700887,-0.496227,-4.618734,-8.467547,non-english_repetition_,9,non,english,repetition,NaN
3357183,non-english_repetition_9,-4.498746,-7.264227,-5.859105,-11.990125,-6.943758,1.109793,-2.667156,-2.415941,-1.606863,...,-2.700887,-0.496227,-4.618734,-8.467547,non-english_repetition_,9,non,english,repetition,NaN

In [66]:
m['target'].unique()

array(['english', 'french', 'german', 'spanish', 'repetition'],
      dtype=object)

In [ ]:
l = pd.read_csv("lawyer_spanish-english_translation_14.csv")
l[['strings', 'sub_num']] = l['file_id'].apply(split_string_number).apply(pd.Series)
split_cols = l['strings'].str.split(r'[_-]', expand=True)
split_cols = split_cols.rename(columns = {0:'word', 1:'prime', 2:'target', 3:'is_target', 4:'idx'})
split_cols = split_cols[['word', 'prime', 'target', 'is_target']]
l = pd.concat([l, split_cols], axis=1)
l

,Fp1,Fpz,Fp2,F7,F3,Fz,F4,F8,FC5,FC1,...,O1,Oz,O2,file_id,strings,sub_num,word,prime,target,is_target
0,-3.73982,-6.016895,-2.239246,-8.976723,-6.872855,-5.268699,-5.138813,-7.065641,-2.230684,-6.802336,...,-7.516586,-4.473102,-2.147145,lawyer_spanish-english_translation_14,lawyer_spanish-english_translation_,14,lawyer,spanish,english,translation
1,-5.36882,-5.608895,-2.640246,-10.622723,-4.969855,-5.007699,-5.015813,-6.987641,-4.051684,-7.047336,...,-7.683586,-3.425102,-2.748145,lawyer_spanish-english_translation_14,lawyer_spanish-english_translation_,14,lawyer,spanish,english,translation
2,-6.76682,-5.492895,-1.878246,-11.490723,-3.859855,-4.319699,-4.555813,-7.214641,-4.897684,-6.872336,...,-7.699586,-2.971102,-3.269145,lawyer_spanish-english_translation_14,lawyer_spanish-english_translation_,14,lawyer,spanish,english,translation
3,-7.98682,-5.669895,-0.123246,-11.564723,-3.619855,-3.398699,-4.154813,-7.603641,-4.911684,-6.400336,...,-7.635586,-3.044102,-3.617145,lawyer_spanish-english_translation_14,lawyer_spanish-english_translation_,14,lawyer,spanish,english,translation
4,-9.05982,-6.009895,2.057754,-11.030723,-4.115855,-2.607699,-4.297813,-7.887641,-4.526684,-5.876336,...,-7.550586,-3.335102,-3.639145,lawyer_spanish-english_translation_14,lawyer_spanish-english_translation_,14,lawyer,spanish,english,translation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,-3.51682,-1.697895,-2.728246,-10.633723,-8.578855,-8.568699,-5.287813,-3.886641,-9.075684,-8.172336,...,1.141414,-1.449102,1.209855,lawyer_spanish-english_translation_14,lawyer_spanish-english_translation_,14,lawyer,spanish,english,translation
252,-0.93682,-0.116895,-3.095246,-7.548723,-7.357855,-7.782699,-3.605812,-2.518641,-6.969684,-7.099336,...,2.041414,-0.141102,2.526855,lawyer_spanish-english_translation_14,lawyer_spanish-english_translation_,14,lawyer,spanish,english,translation
253,3.41818,2.774105,-3.127246,-1.822723,-4.885855,-5.685699,-0.092812,-1.016641,-3.140684,-4.780336,...,3.840414,2.031898,4.475855,lawyer_spanish-english_translation_14,lawyer_spanish-english_translation_,14,lawyer,spanish,english,translation
254,8.76518,6.430105,-2.895246,5.480277,-1.677855,-2.810699,4.534187,0.466359,1.778316,-1.715336,...,6.200414,4.731898,6.817855,lawyer_spanish-english_translation_14,lawyer_spanish-english_translation_,14,lawyer,spanish,english,translation
255,8.76518,6.430105,-2.895246,5.480277,-1.677855,-2.810699,4.534187,0.466359,1.778316,-1.715336,...,6.200414,4.731898,6.817855,lawyer_spanish-english_translation_14,lawyer_spanish-english_translation_,14,lawyer,spanish,english,translation

In [82]:
l = l.drop(columns=['strings'])

In [83]:
f = pd.concat([m,l], join = 'outer')

In [84]:
f

,file_id,Fp1,Fpz,Fp2,F7,F3,Fz,F4,F8,FC5,...,POz,O1,Oz,O2,strings,sub_num,word,prime,target,is_target
0,book_english-english_translation_1,0.105563,-10.123230,-13.193379,6.893438,-7.629562,28.292086,2.719152,-2.486754,-6.934687,...,-12.258789,5.257230,0.080961,-1.445801,book_english-english_translation_,1,book,english,english,translation
1,book_english-english_translation_1,-3.794437,-9.431230,-12.219379,1.226438,-13.299563,13.985086,-1.569848,-7.682754,-4.498687,...,-12.626789,4.125230,-0.084039,0.799199,book_english-english_translation_,1,book,english,english,translation
2,book_english-english_translation_1,-7.023438,-9.685230,-12.414379,-2.416562,-17.288563,6.112086,-3.922848,-10.316754,-3.801687,...,-13.392789,2.746230,-0.500039,2.292199,book_english-english_translation_,1,book,english,english,translation
3,book_english-english_translation_1,-9.825437,-11.147230,-13.928379,-4.398562,-20.232563,3.905086,-4.680848,-10.806754,-4.979687,...,-14.575789,1.150230,-1.167039,3.052199,book_english-english_translation_,1,book,english,english,translation
4,book_english-english_translation_1,-12.493438,-13.672230,-16.416379,-5.623563,-23.102563,4.827086,-4.590848,-10.200754,-7.615687,...,-15.943789,-0.458770,-1.918039,3.352199,book_english-english_translation_,1,book,english,english,translation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,lawyer_spanish-english_translation_14,-3.516820,-1.697895,-2.728246,-10.633723,-8.578855,-8.568699,-5.287813,-3.886641,-9.075684,...,-1.044684,1.141414,-1.449102,1.209855,NaN,14,lawyer,spanish,english,translation
252,lawyer_spanish-english_translation_14,-0.936820,-0.116895,-3.095246,-7.548723,-7.357855,-7.782699,-3.605812,-2.518641,-6.969684,...,-0.334684,2.041414,-0.141102,2.526855,NaN,14,lawyer,spanish,english,translation
253,lawyer_spanish-english_translation_14,3.418180,2.774105,-3.127246,-1.822723,-4.885855,-5.685699,-0.092812,-1.016641,-3.140684,...,1.114316,3.840414,2.031898,4.475855,NaN,14,lawyer,spanish,english,translation
254,lawyer_spanish-english_translation_14,8.765180,6.430105,-2.895246,5.480277,-1.677855,-2.810699,4.534187,0.466359,1.778316,...,3.016316,6.200414,4.731898,6.817855,NaN,14,lawyer,spanish,english,translation
255,lawyer_spanish-english_translation_14,8.765180,6.430105,-2.895246,5.480277,-1.677855,-2.810699,4.534187,0.466359,1.778316,...,3.016316,6.200414,4.731898,6.817855,NaN,14,lawyer,spanish,english,translation

In [85]:
f = f.drop(columns=['strings'])

In [86]:
f

,file_id,Fp1,Fpz,Fp2,F7,F3,Fz,F4,F8,FC5,...,P8,POz,O1,Oz,O2,sub_num,word,prime,target,is_target
0,book_english-english_translation_1,0.105563,-10.123230,-13.193379,6.893438,-7.629562,28.292086,2.719152,-2.486754,-6.934687,...,2.177121,-12.258789,5.257230,0.080961,-1.445801,1,book,english,english,translation
1,book_english-english_translation_1,-3.794437,-9.431230,-12.219379,1.226438,-13.299563,13.985086,-1.569848,-7.682754,-4.498687,...,4.545121,-12.626789,4.125230,-0.084039,0.799199,1,book,english,english,translation
2,book_english-english_translation_1,-7.023438,-9.685230,-12.414379,-2.416562,-17.288563,6.112086,-3.922848,-10.316754,-3.801687,...,5.249121,-13.392789,2.746230,-0.500039,2.292199,1,book,english,english,translation
3,book_english-english_translation_1,-9.825437,-11.147230,-13.928379,-4.398562,-20.232563,3.905086,-4.680848,-10.806754,-4.979687,...,4.145121,-14.575789,1.150230,-1.167039,3.052199,1,book,english,english,translation
4,book_english-english_translation_1,-12.493438,-13.672230,-16.416379,-5.623563,-23.102563,4.827086,-4.590848,-10.200754,-7.615687,...,1.752121,-15.943789,-0.458770,-1.918039,3.352199,1,book,english,english,translation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,lawyer_spanish-english_translation_14,-3.516820,-1.697895,-2.728246,-10.633723,-8.578855,-8.568699,-5.287813,-3.886641,-9.075684,...,5.424855,-1.044684,1.141414,-1.449102,1.209855,14,lawyer,spanish,english,translation
252,lawyer_spanish-english_translation_14,-0.936820,-0.116895,-3.095246,-7.548723,-7.357855,-7.782699,-3.605812,-2.518641,-6.969684,...,6.165855,-0.334684,2.041414,-0.141102,2.526855,14,lawyer,spanish,english,translation
253,lawyer_spanish-english_translation_14,3.418180,2.774105,-3.127246,-1.822723,-4.885855,-5.685699,-0.092812,-1.016641,-3.140684,...,7.705855,1.114316,3.840414,2.031898,4.475855,14,lawyer,spanish,english,translation
254,lawyer_spanish-english_translation_14,8.765180,6.430105,-2.895246,5.480277,-1.677855,-2.810699,4.534187,0.466359,1.778316,...,9.785855,3.016316,6.200414,4.731898,6.817855,14,lawyer,spanish,english,translation
255,lawyer_spanish-english_translation_14,8.765180,6.430105,-2.895246,5.480277,-1.677855,-2.810699,4.534187,0.466359,1.778316,...,9.785855,3.016316,6.200414,4.731898,6.817855,14,lawyer,spanish,english,translation

In [ ]:
f = f.reset_index(drop = True)

In [89]:
f

,file_id,Fp1,Fpz,Fp2,F7,F3,Fz,F4,F8,FC5,...,P8,POz,O1,Oz,O2,sub_num,word,prime,target,is_target
0,book_english-english_translation_1,0.105563,-10.123230,-13.193379,6.893438,-7.629562,28.292086,2.719152,-2.486754,-6.934687,...,2.177121,-12.258789,5.257230,0.080961,-1.445801,1,book,english,english,translation
1,book_english-english_translation_1,-3.794437,-9.431230,-12.219379,1.226438,-13.299563,13.985086,-1.569848,-7.682754,-4.498687,...,4.545121,-12.626789,4.125230,-0.084039,0.799199,1,book,english,english,translation
2,book_english-english_translation_1,-7.023438,-9.685230,-12.414379,-2.416562,-17.288563,6.112086,-3.922848,-10.316754,-3.801687,...,5.249121,-13.392789,2.746230,-0.500039,2.292199,1,book,english,english,translation
3,book_english-english_translation_1,-9.825437,-11.147230,-13.928379,-4.398562,-20.232563,3.905086,-4.680848,-10.806754,-4.979687,...,4.145121,-14.575789,1.150230,-1.167039,3.052199,1,book,english,english,translation
4,book_english-english_translation_1,-12.493438,-13.672230,-16.416379,-5.623563,-23.102563,4.827086,-4.590848,-10.200754,-7.615687,...,1.752121,-15.943789,-0.458770,-1.918039,3.352199,1,book,english,english,translation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5287675,lawyer_spanish-english_translation_14,-3.516820,-1.697895,-2.728246,-10.633723,-8.578855,-8.568699,-5.287813,-3.886641,-9.075684,...,5.424855,-1.044684,1.141414,-1.449102,1.209855,14,lawyer,spanish,english,translation
5287676,lawyer_spanish-english_translation_14,-0.936820,-0.116895,-3.095246,-7.548723,-7.357855,-7.782699,-3.605812,-2.518641,-6.969684,...,6.165855,-0.334684,2.041414,-0.141102,2.526855,14,lawyer,spanish,english,translation
5287677,lawyer_spanish-english_translation_14,3.418180,2.774105,-3.127246,-1.822723,-4.885855,-5.685699,-0.092812,-1.016641,-3.140684,...,7.705855,1.114316,3.840414,2.031898,4.475855,14,lawyer,spanish,english,translation
5287678,lawyer_spanish-english_translation_14,8.765180,6.430105,-2.895246,5.480277,-1.677855,-2.810699,4.534187,0.466359,1.778316,...,9.785855,3.016316,6.200414,4.731898,6.817855,14,lawyer,spanish,english,translation
5287679,lawyer_spanish-english_translation_14,8.765180,6.430105,-2.895246,5.480277,-1.677855,-2.810699,4.534187,0.466359,1.778316,...,9.785855,3.016316,6.200414,4.731898,6.817855,14,lawyer,spanish,english,translation

In [90]:
f.to_csv('complete.csv')